// Public Cloudinary delivery URL; generated by scripts/upload-branding.cjs.
export const LOGO_URL = "https://res.cloudinary.com/eiya3d1b/image/upload/v1790564757/retrack/branding/logo-11a0216c91dc41d2.png";
