// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Retrack.API.Data;

#nullable disable

namespace Retrack.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920074916_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReTrack.Models.BatchQualityCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ActualWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_weight_kg");

                    b.Property<decimal>("AgreedPricePerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("agreed_price_per_kg");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("factory_id");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grade");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_amount");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("net_amount");

                    b.Property<string>("PaymentProofUrl")
                        .HasColumnType("text")
                        .HasColumnName("payment_proof_url");

                    b.Property<decimal>("PlatformFeeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("platform_fee_amount");

                    b.Property<decimal>("PlatformFeePercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("platform_fee_percentage");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.HasIndex("FactoryId");

                    b.ToTable("batch_quality_checks");
                });

            modelBuilder.Entity("ReTrack.Models.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("depots");
                });

            modelBuilder.Entity("ReTrack.Models.DepotStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("StaffType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("staff_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("UserId");

                    b.ToTable("depot_staffs");
                });

            modelBuilder.Entity("ReTrack.Models.Factory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("factories");
                });

            modelBuilder.Entity("ReTrack.Models.FactoryDemand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("factory_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<decimal?>("MaxPricePerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("max_price_per_kg");

                    b.Property<decimal?>("MinPricePerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("min_price_per_kg");

                    b.Property<decimal>("RequiredWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("required_weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("factory_demands");
                });

            modelBuilder.Entity("ReTrack.Models.FactoryDepotPartnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("factory_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("DepotId", "FactoryId")
                        .IsUnique();

                    b.ToTable("factory_depot_partnerships");
                });

            modelBuilder.Entity("ReTrack.Models.FactoryDepotReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("factory_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("DepotId");

                    b.HasIndex("FactoryId");

                    b.ToTable("factory_depot_reviews");
                });

            modelBuilder.Entity("ReTrack.Models.InventoryBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DeclaredWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("declared_weight_kg");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetFactoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_factory_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("TargetFactoryId");

                    b.ToTable("inventory_batches");
                });

            modelBuilder.Entity("ReTrack.Models.PickupRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcceptedCollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_collector_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CheckinImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("checkin_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_amount");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("net_amount");

                    b.Property<string>("PaymentProofUrl")
                        .HasColumnType("text")
                        .HasColumnName("payment_proof_url");

                    b.Property<decimal>("PlatformFeeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("platform_fee_amount");

                    b.Property<decimal>("PlatformFeePercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("platform_fee_percentage");

                    b.Property<DateTime?>("PreferredDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preferred_datetime");

                    b.Property<string>("RequestImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("request_image_url");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetDepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_depot_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedCollectorId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TargetDepotId");

                    b.ToTable("pickup_requests");
                });

            modelBuilder.Entity("ReTrack.Models.PickupRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<Guid>("PickupRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_request_id");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_kg");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("sub_total");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("PickupRequestId");

                    b.ToTable("pickup_request_items");
                });

            modelBuilder.Entity("ReTrack.Models.PlatformTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("fee_amount");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.HasKey("Id");

                    b.ToTable("platform_transactions");
                });

            modelBuilder.Entity("ReTrack.Models.SellerDepotReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<Guid>("PickupRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_request_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("PickupRequestId");

                    b.ToTable("seller_depot_reviews");
                });

            modelBuilder.Entity("ReTrack.Models.SystemConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ConfigKey");

                    b.ToTable("system_configs");

                    b.HasData(
                        new
                        {
                            ConfigKey = "PLATFORM_FEE_PERCENTAGE",
                            ConfigValue = "1.00",
                            Description = "Phí n?n t?ng 1%",
                            UpdatedAt = new DateTime(2026, 9, 20, 7, 49, 15, 238, DateTimeKind.Utc).AddTicks(399)
                        });
                });

            modelBuilder.Entity("ReTrack.Models.TransportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("CheckinDepotImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("checkin_depot_image_url");

                    b.Property<string>("CheckoutFactoryImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("checkout_factory_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.HasIndex("DriverId");

                    b.ToTable("transport_jobs");
                });

            modelBuilder.Entity("ReTrack.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("ReTrack.Models.BatchQualityCheck", b =>
                {
                    b.HasOne("ReTrack.Models.InventoryBatch", "Batch")
                        .WithOne("QualityCheck")
                        .HasForeignKey("ReTrack.Models.BatchQualityCheck", "BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReTrack.Models.Factory", "Factory")
                        .WithMany("QualityChecks")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("ReTrack.Models.Depot", b =>
                {
                    b.HasOne("ReTrack.Models.User", "Owner")
                        .WithMany("OwnedDepots")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ReTrack.Models.DepotStaff", b =>
                {
                    b.HasOne("ReTrack.Models.Depot", "Depot")
                        .WithMany("Staffs")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReTrack.Models.User", "User")
                        .WithMany("DepotStaffs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReTrack.Models.Factory", b =>
                {
                    b.HasOne("ReTrack.Models.User", "Owner")
                        .WithMany("OwnedFactories")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ReTrack.Models.FactoryDemand", b =>
                {
                    b.HasOne("ReTrack.Models.Factory", "Factory")
                        .WithMany("Demands")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("ReTrack.Models.FactoryDepotPartnership", b =>
                {
                    b.HasOne("ReTrack.Models.Depot", "Depot")
                        .WithMany("Partnerships")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReTrack.Models.Factory", "Factory")
                        .WithMany("Partnerships")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("ReTrack.Models.FactoryDepotReview", b =>
                {
                    b.HasOne("ReTrack.Models.InventoryBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReTrack.Models.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReTrack.Models.Factory", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Depot");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("ReTrack.Models.InventoryBatch", b =>
                {
                    b.HasOne("ReTrack.Models.Depot", "Depot")
                        .WithMany("InventoryBatches")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReTrack.Models.Factory", "TargetFactory")
                        .WithMany()
                        .HasForeignKey("TargetFactoryId");

                    b.Navigation("Depot");

                    b.Navigation("TargetFactory");
                });

            modelBuilder.Entity("ReTrack.Models.PickupRequest", b =>
                {
                    b.HasOne("ReTrack.Models.User", "AcceptedCollector")
                        .WithMany()
                        .HasForeignKey("AcceptedCollectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReTrack.Models.User", "Seller")
                        .WithMany("PickupRequests")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReTrack.Models.Depot", "TargetDepot")
                        .WithMany("PickupRequests")
                        .HasForeignKey("TargetDepotId");

                    b.Navigation("AcceptedCollector");

                    b.Navigation("Seller");

                    b.Navigation("TargetDepot");
                });

            modelBuilder.Entity("ReTrack.Models.PickupRequestItem", b =>
                {
                    b.HasOne("ReTrack.Models.PickupRequest", "PickupRequest")
                        .WithMany("Items")
                        .HasForeignKey("PickupRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickupRequest");
                });

            modelBuilder.Entity("ReTrack.Models.SellerDepotReview", b =>
                {
                    b.HasOne("ReTrack.Models.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReTrack.Models.PickupRequest", "PickupRequest")
                        .WithMany("Reviews")
                        .HasForeignKey("PickupRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");

                    b.Navigation("PickupRequest");
                });

            modelBuilder.Entity("ReTrack.Models.TransportJob", b =>
                {
                    b.HasOne("ReTrack.Models.InventoryBatch", "Batch")
                        .WithOne("TransportJob")
                        .HasForeignKey("ReTrack.Models.TransportJob", "BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReTrack.Models.User", "Driver")
                        .WithMany("TransportJobs")
                        .HasForeignKey("DriverId");

                    b.Navigation("Batch");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("ReTrack.Models.Depot", b =>
                {
                    b.Navigation("InventoryBatches");

                    b.Navigation("Partnerships");

                    b.Navigation("PickupRequests");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("ReTrack.Models.Factory", b =>
                {
                    b.Navigation("Demands");

                    b.Navigation("Partnerships");

                    b.Navigation("QualityChecks");
                });

            modelBuilder.Entity("ReTrack.Models.InventoryBatch", b =>
                {
                    b.Navigation("QualityCheck");

                    b.Navigation("TransportJob");
                });

            modelBuilder.Entity("ReTrack.Models.PickupRequest", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ReTrack.Models.User", b =>
                {
                    b.Navigation("DepotStaffs");

                    b.Navigation("OwnedDepots");

                    b.Navigation("OwnedFactories");

                    b.Navigation("PickupRequests");

                    b.Navigation("TransportJobs");
                });
#pragma warning restore 612, 618
        }
    }
}

