// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Retrack.API.Data;

#nullable disable

namespace Retrack.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924014347_FactoryWorkflowExtension")]
    partial class FactoryWorkflowExtension
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Retrack.API.Models.BatchQualityCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ActualWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_weight_kg");

                    b.Property<decimal>("AgreedPricePerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("agreed_price_per_kg");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<decimal?>("ContaminationPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("contamination_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DifferencePercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("difference_percentage");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("factory_id");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grade");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_amount");

                    b.Property<decimal?>("GrossWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_weight_kg");

                    b.Property<string>("InvoiceFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("invoice_file_url");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<string>("InvoiceStatus")
                        .HasColumnType("text")
                        .HasColumnName("invoice_status");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<decimal?>("MoisturePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("moisture_percent");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("net_amount");

                    b.Property<string>("PaymentProofUrl")
                        .HasColumnType("text")
                        .HasColumnName("payment_proof_url");

                    b.Property<decimal>("PlatformFeeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("platform_fee_amount");

                    b.Property<decimal>("PlatformFeePercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("platform_fee_percentage");

                    b.Property<decimal?>("PurityPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("purity_percent");

                    b.Property<string>("QualityNote")
                        .HasColumnType("text")
                        .HasColumnName("quality_note");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<decimal?>("TareWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("tare_weight_kg");

                    b.Property<string>("TicketImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("ticket_image_url");

                    b.Property<string>("TicketNumber")
                        .HasColumnType("text")
                        .HasColumnName("ticket_number");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.HasIndex("FactoryId");

                    b.ToTable("batch_quality_checks");
                });

            modelBuilder.Entity("Retrack.API.Models.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("depots");
                });

            modelBuilder.Entity("Retrack.API.Models.DepotStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("StaffType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("staff_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("UserId");

                    b.ToTable("depot_staffs");
                });

            modelBuilder.Entity("Retrack.API.Models.Factory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptedMaterialsCsv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accepted_materials");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BusinessLicenseUrl")
                        .HasColumnType("text")
                        .HasColumnName("business_license_url");

                    b.Property<decimal>("CapacityKgPerMonth")
                        .HasColumnType("numeric")
                        .HasColumnName("capacity_kg_per_month");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnvironmentalLicenseUrl")
                        .HasColumnType("text")
                        .HasColumnName("environmental_license_url");

                    b.Property<string>("IndustrialZone")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("industrial_zone");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<decimal>("MinimumPurityPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("minimum_purity_percent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_code");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("factories");
                });

            modelBuilder.Entity("Retrack.API.Models.FactoryDemand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("factory_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<decimal?>("MaxPricePerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("max_price_per_kg");

                    b.Property<decimal?>("MinPricePerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("min_price_per_kg");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<decimal>("RequiredWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("required_weight_kg");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("factory_demands");
                });

            modelBuilder.Entity("Retrack.API.Models.FactoryDepotPartnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("factory_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("DepotId", "FactoryId")
                        .IsUnique();

                    b.ToTable("factory_depot_partnerships");
                });

            modelBuilder.Entity("Retrack.API.Models.FactoryDepotReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("factory_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("DepotId");

                    b.HasIndex("FactoryId");

                    b.ToTable("factory_depot_reviews");
                });

            modelBuilder.Entity("Retrack.API.Models.InventoryBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_weight_kg");

                    b.Property<decimal?>("AgreedPricePerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("agreed_price_per_kg");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DeclaredWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("declared_weight_kg");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FactoryDecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("factory_decided_at");

                    b.Property<DateTime?>("FactoryReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("factory_received_at");

                    b.Property<decimal?>("GrossAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_amount");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<decimal?>("NetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("net_amount");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text")
                        .HasColumnName("payment_reference");

                    b.Property<decimal?>("PlatformFeeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("platform_fee_amount");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetFactoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_factory_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("TargetFactoryId");

                    b.ToTable("inventory_batches");
                });

            modelBuilder.Entity("Retrack.API.Models.MarketPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_kg");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.ToTable("market_prices");
                });

            modelBuilder.Entity("Retrack.API.Models.PickupRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcceptedCollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_collector_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CheckinImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("checkin_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_amount");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("net_amount");

                    b.Property<string>("PaymentProofUrl")
                        .HasColumnType("text")
                        .HasColumnName("payment_proof_url");

                    b.Property<decimal>("PlatformFeeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("platform_fee_amount");

                    b.Property<decimal>("PlatformFeePercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("platform_fee_percentage");

                    b.Property<DateTime?>("PreferredDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preferred_datetime");

                    b.Property<string>("RequestImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("request_image_url");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetDepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_depot_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedCollectorId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TargetDepotId");

                    b.ToTable("pickup_requests");
                });

            modelBuilder.Entity("Retrack.API.Models.PickupRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<Guid>("PickupRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_request_id");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_kg");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("sub_total");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("PickupRequestId");

                    b.ToTable("pickup_request_items");
                });

            modelBuilder.Entity("Retrack.API.Models.PlatformTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("fee_amount");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.HasKey("Id");

                    b.ToTable("platform_transactions");
                });

            modelBuilder.Entity("Retrack.API.Models.SellerDepotReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<Guid>("PickupRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_request_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("PickupRequestId");

                    b.ToTable("seller_depot_reviews");
                });

            modelBuilder.Entity("Retrack.API.Models.SystemConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ConfigKey");

                    b.ToTable("system_configs");

                    b.HasData(
                        new
                        {
                            ConfigKey = "PLATFORM_FEE_PERCENTAGE",
                            ConfigValue = "1.00",
                            Description = "Phí nền tảng 1%",
                            UpdatedAt = new DateTime(2026, 9, 24, 1, 43, 46, 834, DateTimeKind.Utc).AddTicks(9189)
                        });
                });

            modelBuilder.Entity("Retrack.API.Models.TransportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("CheckinDepotImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("checkin_depot_image_url");

                    b.Property<string>("CheckoutFactoryImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("checkout_factory_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.HasIndex("DriverId");

                    b.ToTable("transport_jobs");
                });

            modelBuilder.Entity("Retrack.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Retrack.API.Models.BatchQualityCheck", b =>
                {
                    b.HasOne("Retrack.API.Models.InventoryBatch", "Batch")
                        .WithOne("QualityCheck")
                        .HasForeignKey("Retrack.API.Models.BatchQualityCheck", "BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retrack.API.Models.Factory", "Factory")
                        .WithMany("QualityChecks")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("Retrack.API.Models.Depot", b =>
                {
                    b.HasOne("Retrack.API.Models.User", "Owner")
                        .WithMany("OwnedDepots")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Retrack.API.Models.DepotStaff", b =>
                {
                    b.HasOne("Retrack.API.Models.Depot", "Depot")
                        .WithMany("Staffs")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retrack.API.Models.User", "User")
                        .WithMany("DepotStaffs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Retrack.API.Models.Factory", b =>
                {
                    b.HasOne("Retrack.API.Models.User", "Owner")
                        .WithMany("OwnedFactories")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Retrack.API.Models.FactoryDemand", b =>
                {
                    b.HasOne("Retrack.API.Models.Factory", "Factory")
                        .WithMany("Demands")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("Retrack.API.Models.FactoryDepotPartnership", b =>
                {
                    b.HasOne("Retrack.API.Models.Depot", "Depot")
                        .WithMany("Partnerships")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retrack.API.Models.Factory", "Factory")
                        .WithMany("Partnerships")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("Retrack.API.Models.FactoryDepotReview", b =>
                {
                    b.HasOne("Retrack.API.Models.InventoryBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retrack.API.Models.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retrack.API.Models.Factory", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Depot");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("Retrack.API.Models.InventoryBatch", b =>
                {
                    b.HasOne("Retrack.API.Models.Depot", "Depot")
                        .WithMany("InventoryBatches")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retrack.API.Models.Factory", "TargetFactory")
                        .WithMany()
                        .HasForeignKey("TargetFactoryId");

                    b.Navigation("Depot");

                    b.Navigation("TargetFactory");
                });

            modelBuilder.Entity("Retrack.API.Models.PickupRequest", b =>
                {
                    b.HasOne("Retrack.API.Models.User", "AcceptedCollector")
                        .WithMany()
                        .HasForeignKey("AcceptedCollectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Retrack.API.Models.User", "Seller")
                        .WithMany("PickupRequests")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrack.API.Models.Depot", "TargetDepot")
                        .WithMany("PickupRequests")
                        .HasForeignKey("TargetDepotId");

                    b.Navigation("AcceptedCollector");

                    b.Navigation("Seller");

                    b.Navigation("TargetDepot");
                });

            modelBuilder.Entity("Retrack.API.Models.PickupRequestItem", b =>
                {
                    b.HasOne("Retrack.API.Models.PickupRequest", "PickupRequest")
                        .WithMany("Items")
                        .HasForeignKey("PickupRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickupRequest");
                });

            modelBuilder.Entity("Retrack.API.Models.SellerDepotReview", b =>
                {
                    b.HasOne("Retrack.API.Models.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retrack.API.Models.PickupRequest", "PickupRequest")
                        .WithMany("Reviews")
                        .HasForeignKey("PickupRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");

                    b.Navigation("PickupRequest");
                });

            modelBuilder.Entity("Retrack.API.Models.TransportJob", b =>
                {
                    b.HasOne("Retrack.API.Models.InventoryBatch", "Batch")
                        .WithOne("TransportJob")
                        .HasForeignKey("Retrack.API.Models.TransportJob", "BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retrack.API.Models.User", "Driver")
                        .WithMany("TransportJobs")
                        .HasForeignKey("DriverId");

                    b.Navigation("Batch");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Retrack.API.Models.Depot", b =>
                {
                    b.Navigation("InventoryBatches");

                    b.Navigation("Partnerships");

                    b.Navigation("PickupRequests");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("Retrack.API.Models.Factory", b =>
                {
                    b.Navigation("Demands");

                    b.Navigation("Partnerships");

                    b.Navigation("QualityChecks");
                });

            modelBuilder.Entity("Retrack.API.Models.InventoryBatch", b =>
                {
                    b.Navigation("QualityCheck");

                    b.Navigation("TransportJob");
                });

            modelBuilder.Entity("Retrack.API.Models.PickupRequest", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Retrack.API.Models.User", b =>
                {
                    b.Navigation("DepotStaffs");

                    b.Navigation("OwnedDepots");

                    b.Navigation("OwnedFactories");

                    b.Navigation("PickupRequests");

                    b.Navigation("TransportJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
